apiVersion: apps/v1
kind: Deployment
metadata: 
  name: aes-encryption-service
  labels:
    app: aes-encryption-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aes-encryption-service
  template:
    metadata:
      labels:
        app: aes-encryption-service
    spec:
      containers:
      - name: aes-encryption-service
        image: docker.io/darylmcbride/aes-encryption-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aes-encrpytion-service
spec:
  selector:
    app: aes-encryption-service
  ports: 
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
