apiVersion: apps/v1
kind: Deployment
metadata: 
  name: authentication-client
  labels:
    app: authentication-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-client
  template:
    metadata:
      labels:
        app: authentication-client
    spec:
      containers:
      - name: authentication-client
        image: docker.io/darylmcbride/authentication-client
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-client
spec:
  selector:
    app: authentication-client
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
