apiVersion: apps/v1
kind: Deployment
metadata: 
  name: email-service
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: docker.io/${DOCKER_LOGIN}/email-service
        ports:
        - containerPort: 3000
        env:
        - name: GMAIL_USER
          value: ilovedocker123@gmail.com
        - name: GMAIL_PASS
          value: ilovedocker1!
        - name: SERVICE_NAME
          value: "login service thingy"
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports: 
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
