apiVersion: v1 
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:          
  containers: 
  - name: mongo
    image: docker.io/library/mongo
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: database
      mountPath: "/data/db/"
      readOnly: false
  volumes:
  - name: database
    persistentVolumeClaim:
      claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

