apiVersion: apps/v1
kind: Deployment
metadata: 
  name: session-token-service
  labels:
    app: session-token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-token-service
  template:
    metadata:
      labels:
        app: session-token-service
    spec:
      containers:
      - name: session-token-service
        image: docker.io/${DOCKER_LOGIN}/session-token-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: session-token-service
spec:
  selector:
    app: session-token-service
  ports: 
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
